services:
  db:
    env_file:
      - .env
    container_name: postgreslocal
    image: postgres:16-alpine3.19
    volumes:
      - ${LOCAL_PATH_POSTGRES_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432